from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^index',views.index,name='index'),
    url(r'^register',views.register,name='register'),
    url(r'^registration',views.registration,name='registration'),
    url(r'^validatelogin',views.validatelogin,name='validatelogin'),
    url(r'^welcome',views.welcome,name='welcome'),
    url(r'^user_dashboard',views.user_dashboard,name='user_dashboard'),
    url(r'^math_ncert',views.math_ncert,name='math_ncert'),
    url(r'^math_mcq',views.math_mcq,name='math_mcq'),
    url(r'^physics_ncert', views.physics_ncert, name='physics_ncert'),
    url(r'^physics_mcq', views.physics_mcq, name='physics_mcq'),
    url(r'^chemistry_ncert', views.chemistry_ncert, name='chemistry_ncert'),
    url(r'^chemistry_mcq', views.chemistry_mcq, name='chemistry_mcq'),
    url(r'^biology_ncert', views.biology_ncert, name='biology_ncert'),
    url(r'^biology_mcq', views.biology_mcq, name='biology_mcq'),
    url(r'^history_ncert', views.history_ncert, name='history_ncert'),
    url(r'^history_mcq', views.history_mcq, name='history_mcq'),
    url(r'^civics_ncert', views.civics_ncert, name='civics_ncert'),
    url(r'^civics_mcq', views.civics_mcq, name='civics_mcq'),
    url(r'^geo_ncert', views.geo_ncert, name='geo_ncert'),
    url(r'^geo_mcq', views.geo_mcq, name='geo_mcq'),
    url(r'^comp_ncert', views.comp_ncert, name='comp_ncert'),
    url(r'^comp_mcq', views.comp_mcq, name='comp_mcq'),
    url(r'^none',views.none,name='none'),
    url(r'^logout',views.logout,name='logout'),
]