# Generated by Django 3.1.1 on 2021-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
