# Generated by Django 3.2.7 on 2021-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='adminid',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
