# Generated by Django 3.2.7 on 2021-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0002_alter_adminlogin_adminid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject', models.TextField(max_length=35, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
