# Generated by Django 3.2.7 on 2021-10-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0003_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
