# Generated by Django 3.1.1 on 2021-10-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0005_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
