# Generated by Django 3.1.1 on 2021-10-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0006_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
    ]
