# Generated by Django 3.2.7 on 2021-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0007_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SUBJECT',
        ),
    ]
