# Generated by Django 3.2.7 on 2021-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0008_auto_20211019_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('class_name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
    ]
