# Generated by Django 3.2.7 on 2021-10-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0009_myclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(max_length=2)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
