# Generated by Django 3.2.7 on 2021-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_controlapp', '0011_pdf_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='cls',
            field=models.CharField(max_length=20),
        ),
    ]
